# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    shell: bash -leo pipefail {0}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: nelonoel/branch-name@v1.0.1
      - run: echo BRANCH=${BRANCH_NAME}

      - name: Analyze Test Result
        if: always()
        shell: bash
        run: |
          cd test-results
          python3 ../tools/analyze_test_result.py result.xml
          echo TEST_RESULT
          cat TEST_RESULT
          echo TEST_COLOR
          cat TEST_COLOR
          cat TEST_RESULT >> $GITHUB_ENV
          cat TEST_COLOR >> $GITHUB_ENV

      - name: Publish Test Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        if: always()
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: 6a483243c9783b738a269f26ebcc0863
          filename: try_badge_${{ env.BRANCH_NAME }}.json
          label: Test Result
          message: ${{ env.TEST_RESULT }}
          color: ${{ env.TEST_COLOR }}

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: test-results/**/*.xml
